map $http_accept_encoding $compressed_ext {
    default "";
    "~*zstd" ".zst";
    "~*br" ".br";
    "~*gzip" ".gz";
}

map $compressed_ext $compressed_enc {
    ".zst" "zstd";
    ".br" "br";
    ".gz" "gzip";
}

server {
    listen 80;
    server_name oms.vegecoop.net localhost;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name oms.vegecoop.net localhost;

    ssl_certificate /etc/letsencrypt/live/oms.vegecoop.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/oms.vegecoop.net/privkey.pem;

    client_max_body_size 25M;

    # Map nested extensions back to their real content type
    include mime.types;
    types {
        application/javascript js.zst js.br js.gz;
        text/css css.zst css.br css.gz;
        text/html html.zst html.br html.gz;
        image/svg+xml svg.zst svg.br svg.gz;
        application/json json.zst json.br json.gz;
        application/wasm wasm.zst wasm.br wasm.gz;
    }

    # Handle compressable assets
    location ~* \.(?:js|css|html|svg|json|wasm)$ {
        root /usr/share/nginx/html;
        add_header Vary Accept-Encoding;

        if ($uri = /index.html) {
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            expires off;
        }

        if (-f $document_root$uri$compressed_ext) {
            rewrite ^(.*)$ $1$compressed_ext last;
        }

        try_files $uri $uri/ /index.html;
    }

    # Handle the rewritten requests to compressed files
    location ~* \.(?:js|css|html|svg|json|wasm)\.(?:zst|br|gz)$ {
        root /usr/share/nginx/html;
        add_header Content-Encoding $compressed_enc;
        add_header Vary Accept-Encoding;

        if ($uri ~* \.html\.(?:zst|br|gz)$) {
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            expires off;
        }
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://server:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_read_timeout 120s;
        proxy_connect_timeout 10s;
        proxy_send_timeout 120s;
    }
}
