import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Import all models
import B2BPartner from './models/B2BPartner.js';
import Case from './models/Case.js';
import Claim from './models/Claim.js';
import Employee from './models/Employee.js';
import Option from './models/Option.js';
import Settlement from './models/Settlement.js';
import User from './models/User.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..'); // Points to e:\OMS\

const models = [
  { name: 'User', model: User, desc: 'Used for authentication and authorization.' },
  { name: 'Employee', model: Employee, desc: 'Stores detailed staff profiles and HR information.' },
  { name: 'Claim', model: Claim, desc: 'Represents an expense claim submitted by an employee.' },
  { name: 'Case', model: Case, desc: 'Represents an approved expense or a financial case that needs to be settled or collected.' },
  { name: 'Settlement', model: Settlement, desc: 'Represents the actual transaction or payment record settling a specific Case.' },
  { name: 'B2BPartner', model: B2BPartner, desc: 'Stores details about business partners or clients.' },
  { name: 'Option', model: Option, desc: 'Used to populate dynamic dropdowns or configuration lists.' }
];

function getFields(schema) {
  const fields = [];
  schema.eachPath((pathname, schemaType) => {
    if (pathname === '__v') return;
    
    // Attempt to handle nested paths visually
    const indent = pathname.includes('.') ? '  ' : '';
    let typeName = schemaType.instance || schemaType.options.type?.name || 'Mixed';
    
    if (schemaType.options.ref) {
      typeName += ` (Ref: ${schemaType.options.ref})`;
    }
    
    if (Array.isArray(schemaType.options.type)) {
      typeName = 'Array';
    }

    const isRequired = schemaType.options.required ? 'required' : '';
    let defaultVal = schemaType.options.default;
    if (typeof defaultVal === 'function') defaultVal = 'Function';
    const hasDefault = defaultVal !== undefined ? `default: ${defaultVal}` : '';
    const isUnique = schemaType.options.unique ? 'unique' : '';
    const isEnum = schemaType.options.enum ? `enum: [${schemaType.options.enum.join(', ')}]` : '';
    
    let opts = [isRequired, isUnique, isEnum, hasDefault].filter(Boolean).join(', ');
    if (opts) opts = ` (${opts})`;

    fields.push(`${indent}- \`${pathname}\` - **${typeName}**${opts}`);
  });
  return fields;
}

let markdown = `# Database Schema Details\n\n`;
markdown += `> This file is auto-generated by \`server/generate_schema_docs.js\`. Do not edit manually.\n\n`;
markdown += `The application uses **MongoDB** with **Mongoose**.\n\n`;

markdown += `## Schema Details\n\n`;

models.forEach(({ name, model, desc }) => {
  markdown += `### ${name}\n`;
  markdown += `${desc}\n\n`;
  const fields = getFields(model.schema);
  markdown += fields.join('\n') + '\n\n';
});

const outputPath = path.join(rootDir, 'database_schema.md');
fs.writeFileSync(outputPath, markdown);
console.log(`Schema documentation successfully generated at ${outputPath}`);
